=== Abdalla-Mohamed/chatProject/iti chat client/src/message/services/MessageSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"	
           elementFormDefault="unqualified">

    <xs:element name="massage" type="massageType" />
    <xs:complexType name="massageType">
        <xs:sequence>
            <xs:element name="msg" type="msgc" minOccurs="1" maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="msgc">
        <xs:sequence>
            <xs:element name="from" type="xs:string"/>
            <xs:element name="to" type="xs:string"/>
            <xs:element name="date" type="xs:string"/>
            <xs:element name="body" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="color" type="xs:string"/>
        <xs:attribute name="size" type="xs:int"/>
        <xs:attribute name="font" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== Abdalla-Mohamed/chatProject/iti chat client/src/message/services/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<massage
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='MessageSchema.xsd'>
    <msg color="red" font="arial" size="20">
        <from>aaaaaa</from>
        <to>aaaaaaaaaaaaa</to>
        <date>aaaaaaaaaa</date>
        <body>aaaaaaaaaaaaa</body>
    </msg>
    <msg color="black" font="arial" size="18">
        <from>bbbbbbbbbb</from>
        <to>bbbbbbbbbbbb</to>
        <date>bbbbbbbbbbbbb</date>
        <body>bbbbbbbbbbbbb</body>
    </msg>
    <msg color="green" font="arial" size="12">
        <from>wwwwwwwwwwww</from>
        <to>wwwwwwwwwwww</to>
        <date>wwwwwwwwwwwwwww</date>
        <body>wwwwwwwwwwwwww</body>
    </msg>

</massage>
